# Generated by Django 4.2.6 on 2023-11-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('nit', models.TextField(max_length=200)),
                ('slogan', models.TextField(max_length=200)),
                ('icon', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCountry', models.TextField(max_length=200)),
                ('idDepto', models.TextField(max_length=200)),
                ('idCity', models.TextField(max_length=200)),
                ('adress', models.TextField(max_length=200)),
                ('grades', models.TextField(max_length=200)),
                ('minutes', models.TextField(max_length=200)),
                ('seconds', models.TextField(max_length=200)),
                ('open', models.BooleanField()),
                ('description', models.TextField(max_length=900)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAdressHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField()),
                ('mondayStart', models.BigIntegerField(null=True)),
                ('mondayFinish', models.BigIntegerField(null=True)),
                ('tuesday', models.BooleanField()),
                ('tuesdayStart', models.BigIntegerField(null=True)),
                ('tuesdayFinish', models.BigIntegerField(null=True)),
                ('wednesday', models.BooleanField()),
                ('wednesdayStart', models.BigIntegerField(null=True)),
                ('wednesdayFinish', models.BigIntegerField(null=True)),
                ('thursday', models.BooleanField()),
                ('thursdayStart', models.BigIntegerField(null=True)),
                ('thursdayFinish', models.BigIntegerField(null=True)),
                ('friday', models.BooleanField()),
                ('fridayStart', models.BigIntegerField(null=True)),
                ('fridayFinish', models.BigIntegerField(null=True)),
                ('saturday', models.BooleanField()),
                ('saturdayStart', models.BigIntegerField(null=True)),
                ('saturdayFinish', models.BigIntegerField(null=True)),
                ('sunday', models.BooleanField()),
                ('sundayStart', models.BigIntegerField(null=True)),
                ('sundayFinish', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.company')),
                ('idCompanyAdress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.companyadress')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCompanyAdressHours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.companyadresshours')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(max_length=900)),
                ('responsible', models.TextField(max_length=500)),
                ('signature', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sportType', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourstart', models.DateTimeField()),
                ('hourFinish', models.DateTimeField()),
                ('observations', models.TextField(max_length=900)),
                ('jsonUsersChat', models.JSONField()),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('jsonPermissions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sportType', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('password', models.TextField(max_length=900)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.BigIntegerField()),
                ('observations', models.TextField(max_length=900)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idClient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.users')),
                ('idReservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('nit', models.TextField(max_length=500)),
                ('name', models.TextField(max_length=500)),
                ('address', models.TextField(max_length=500)),
                ('phone', models.TextField(max_length=500)),
                ('email', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idReservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.reservation')),
                ('idTypePay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.typepay')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationChatPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.BigIntegerField()),
                ('sender', models.BigIntegerField()),
                ('message', models.TextField(max_length=500)),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idReservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.BigIntegerField()),
                ('sender', models.BigIntegerField()),
                ('message', models.TextField(max_length=500)),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idReservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='idClient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.users'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='idCompanyService',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.companyservices'),
        ),
        migrations.CreateModel(
            name='DocumentsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.users')),
            ],
        ),
        migrations.AddField(
            model_name='companyservices',
            name='idServices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.service'),
        ),
        migrations.CreateModel(
            name='CompanyPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.company')),
                ('idCompanyAdress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.companyadress')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.company')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.company')),
                ('idContract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.contract')),
                ('idRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.role')),
                ('idUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.users')),
            ],
        ),
    ]
